# Generated by Django 3.2.9 on 2021-11-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_survey_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='multiple_choice',
            field=models.BooleanField(),
        ),
    ]
